import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1779180317329 implements MigrationInterface {
    name = 'Migration1779180317329'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "stage_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "max_duration_days" integer, "canNotify" boolean NOT NULL DEFAULT false, "canScore" boolean NOT NULL DEFAULT false, "instructions" text, "isActive" boolean NOT NULL DEFAULT true, "category" character varying(100), "created_by" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_04083fb6f4ba564d12e50aab682" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pipeline_stages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pipeline_id" uuid NOT NULL, "stage_template_id" uuid NOT NULL, "stage_order" integer NOT NULL, "estimated_duration_days" integer, "sendNotification" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97b60e4dae25fc060f2f5e86300" UNIQUE ("pipeline_id", "stage_order"), CONSTRAINT "CHK_5fe35857edd7b50b30b0621ec9" CHECK (stage_order > 0), CONSTRAINT "PK_92e43270eace072ad5182fc08e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recruitment_pipelines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "version" character varying(20) NOT NULL DEFAULT '1.0', "isDefault" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "isTemplate" boolean NOT NULL DEFAULT false, "category" character varying(100), "usageCount" integer NOT NULL DEFAULT '0', "created_by" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_3f5e0375805af0cab42d33d260e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "job_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" character varying(255), "code" character varying(50), "color" character varying(7), "icon" character varying(255), "sortOrder" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "created_by" character varying NOT NULL, "updated_by" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_2e5f6c46d136907967008b9bb68" UNIQUE ("name"), CONSTRAINT "PK_a3558e7de1e1252863bc01af86f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "departments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "code" character varying(50), "description" text, "isActive" boolean NOT NULL DEFAULT true, "created_by" character varying NOT NULL, "updated_by" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by" character varying, CONSTRAINT "UQ_8681da666ad9699d568b3e91064" UNIQUE ("name"), CONSTRAINT "UQ_91fddbe23e927e1e525c152baa3" UNIQUE ("code"), CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."vacancies_status_enum" AS ENUM('draft', 'published', 'paused', 'closed', 'archived')`);
        await queryRunner.query(`CREATE TYPE "public"."vacancies_jobtype_enum" AS ENUM('recruitment', 'assessment')`);
        await queryRunner.query(`CREATE TYPE "public"."vacancies_employmenttype_enum" AS ENUM('full_time', 'part_time', 'contract', 'internship', 'freelance')`);
        await queryRunner.query(`CREATE TYPE "public"."vacancies_workmodel_enum" AS ENUM('on_site', 'hybrid', 'remote')`);
        await queryRunner.query(`CREATE TYPE "public"."vacancies_salaryperiod_enum" AS ENUM('hourly', 'daily', 'weekly', 'monthly', 'yearly')`);
        await queryRunner.query(`CREATE TYPE "public"."vacancies_requirededucation_enum" AS ENUM('1', '2', '3', '4', '5', '0')`);
        await queryRunner.query(`CREATE TABLE "vacancies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "jobCode" character varying(50), "description" text, "responsibilities" text, "requirements" text, "status" "public"."vacancies_status_enum" NOT NULL DEFAULT 'draft', "jobType" "public"."vacancies_jobtype_enum" NOT NULL DEFAULT 'recruitment', "employmentType" "public"."vacancies_employmenttype_enum" NOT NULL, "workModel" "public"."vacancies_workmodel_enum" NOT NULL DEFAULT 'on_site', "startDate" date, "endDate" date, "isLimitApplicantEnabled" boolean NOT NULL DEFAULT false, "applicantLimit" integer, "isLimitHiredEnabled" boolean NOT NULL DEFAULT false, "hiredLimit" integer, "officeAddresses" json, "department_id" uuid, "salaryMin" integer, "salaryMax" integer, "salaryPeriod" "public"."vacancies_salaryperiod_enum", "currency" character varying(3) NOT NULL DEFAULT 'IDR', "generatedPosterUrl" character varying(500), "posterConfiguration" json, "pipeline_id" uuid, "job_category_id" uuid, "requiredEducation" "public"."vacancies_requirededucation_enum", "requiredExperienceYears" integer, "relevant_major" character varying(255), "role_description" text, "required_skills" text array, "hoursPerWeekMin" integer, "hoursPerWeekMax" integer, "created_by" character varying NOT NULL, "updated_by" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by" character varying, CONSTRAINT "UQ_eea303e7dfecc2a7201742d5a8b" UNIQUE ("jobCode"), CONSTRAINT "PK_3b45154a366568190cc15be2906" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."stage_activities_status_enum" AS ENUM('pending', 'in_progress', 'done', 'failed')`);
        await queryRunner.query(`CREATE TABLE "stage_activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "application_id" uuid NOT NULL, "stage_id" uuid NOT NULL, "notes" text, "score" numeric(10,2), "performed_by" character varying, "status" "public"."stage_activities_status_enum" NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b8c86d418a59375e68aff7c646d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "application_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "application_id" uuid NOT NULL, "notes" text NOT NULL, "createdBy" character varying(100), "updatedBy" character varying(100), "isPrivate" boolean NOT NULL DEFAULT false, "category" character varying(50), "priority" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_db708de5fa99541ad52a1f907de" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d3769eb65b81f027908bdcd0e1" ON "application_notes" ("application_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."applications_status_enum" AS ENUM('new', 'applied', 'hired', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicationNumber" character varying(50) NOT NULL, "applicant_id" uuid NOT NULL, "vacancy_id" uuid NOT NULL, "pipeline_id" uuid NOT NULL, "current_stage_id" uuid, "status" "public"."applications_status_enum" NOT NULL DEFAULT 'applied', "coverLetter" text, "expectedStartDate" date, "source" character varying(100), "customSource" character varying(255), "applied_at" TIMESTAMP NOT NULL DEFAULT now(), "completed_at" TIMESTAMP, "currentScore" integer, "currentNotes" text, "lastActivityAt" TIMESTAMP, "isTalentPool" boolean NOT NULL DEFAULT false, "screening_status" character varying(20), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_cbe9cb2d37267b0fb1bcf49b705" UNIQUE ("applicationNumber"), CONSTRAINT "PK_938c0a27255637bde919591888f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9212e477141318a97e35701ef8" ON "applications" ("vacancy_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."applicant_addresses_addresstype_enum" AS ENUM('current', 'registered')`);
        await queryRunner.query(`CREATE TABLE "applicant_addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicant_id" uuid NOT NULL, "province" character varying(100) NOT NULL, "regency" character varying(100) NOT NULL, "district" character varying(100) NOT NULL, "village" character varying(100) NOT NULL, "fullAddress" text NOT NULL, "postalCode" character varying(10) NOT NULL DEFAULT 'ID', "addressType" "public"."applicant_addresses_addresstype_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_b0382f18e2253a3be85cafe90ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."applicant_job_histories_employeestatus_enum" AS ENUM('full_time', 'part_time', 'contract', 'internship', 'freelance', 'temporary')`);
        await queryRunner.query(`CREATE TABLE "applicant_job_histories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicant_id" uuid NOT NULL, "cv_document_id" uuid, "employeeStatus" "public"."applicant_job_histories_employeestatus_enum", "position" character varying(255), "company" character varying(255), "startDate" date NOT NULL, "endDate" date, "duration_years" double precision, "location" character varying(255), "description" text, "achievements" text, "order" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_98c09ee019ed2af1ebabd80fda0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cv_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "application_id" uuid NOT NULL, "applicant_name" character varying(255), "skills" text array, "parsed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_13f6e65f840ee1723474d3a2e20" UNIQUE ("application_id"), CONSTRAINT "REL_13f6e65f840ee1723474d3a2e2" UNIQUE ("application_id"), CONSTRAINT "PK_21adace014b91999c44d43fa988" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."applicant_educations_level_enum" AS ENUM('1', '2', '3', '4', '5', '0')`);
        await queryRunner.query(`CREATE TABLE "applicant_educations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicant_id" uuid NOT NULL, "cv_document_id" uuid, "level" "public"."applicant_educations_level_enum", "schoolName" character varying(255), "major" character varying(100), "degree" character varying(100), "gpa" numeric(3,2), "startMonth" character varying(7), "endMonth" character varying(7), "diplomaFileName" character varying(255), "order" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_a260db8b7c5f00e20d535755886" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "applicant_project_histories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicant_id" uuid NOT NULL, "projectName" character varying(255) NOT NULL, "position" character varying(255) NOT NULL, "year" character varying(4), "projectLink" character varying(500), "description" text, "technologies" text, "achievements" text, "order" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_cd4997b39eacc12f7e4d4ac04f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."applicant_identities_identitytype_enum" AS ENUM('ktp', 'sim', 'passport')`);
        await queryRunner.query(`CREATE TABLE "applicant_identities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicant_id" uuid NOT NULL, "identityType" "public"."applicant_identities_identitytype_enum" NOT NULL, "identityNumber" character varying(50) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_0b66ac5ed1f8c8b61b7aad17abc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "applicant_sources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" character varying(255), "isActive" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_c566f9880b1fac55d58785c0ebd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."applicants_gender_enum" AS ENUM('male', 'female')`);
        await queryRunner.query(`CREATE TYPE "public"."applicants_maritalstatus_enum" AS ENUM('single', 'married', 'divorced', 'widowed')`);
        await queryRunner.query(`CREATE TYPE "public"."applicants_availability_enum" AS ENUM('immediately', 'one_week', 'two_weeks', 'one_month', 'specific_date')`);
        await queryRunner.query(`CREATE TABLE "applicants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "fullName" character varying(100) NOT NULL, "phone" character varying(20) NOT NULL, "alternativePhone" character varying(20), "gender" "public"."applicants_gender_enum", "maritalStatus" "public"."applicants_maritalstatus_enum", "placeOfBirth" character varying(100), "dateOfBirth" date, "photoUrl" character varying(500), "cvUrl" character varying(500), "linkedinUrl" character varying(500), "portfolioUrl" character varying(500), "socialMediaUrl" character varying(500), "isInternal" boolean NOT NULL DEFAULT false, "availability" "public"."applicants_availability_enum", "availabilityAt" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_cf1d183c497a68c4f07fe62d808" UNIQUE ("email"), CONSTRAINT "PK_c02ec3c46124479ce758ca50943" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."files_filetype_enum" AS ENUM('photo', 'cv', 'cover_letter', 'portfolio', 'certificate', 'identity_document', 'job_description', 'company_logo', 'other')`);
        await queryRunner.query(`CREATE TABLE "files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fileName" character varying(255) NOT NULL, "originalName" character varying(255) NOT NULL, "filePath" character varying(500) NOT NULL, "fileSize" bigint NOT NULL, "mimeType" character varying(100) NOT NULL, "bucket" character varying(100) NOT NULL, "fileType" "public"."files_filetype_enum" NOT NULL, "description" character varying(500), "uploaded_by" uuid, "relatedEntity" character varying(100), "relatedEntityId" uuid, "isActive" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_6c16b9093a142e0e7613b04a3d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "stage_template_id" uuid, "triggerEvent" character varying(100) NOT NULL, "subjectTemplate" text NOT NULL, "bodyTemplate" text NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_76f0fc48b8d057d2ae7f3a2848a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."system_configurations_configtype_enum" AS ENUM('text', 'image', 'email', 'phone', 'url', 'json', 'boolean', 'number')`);
        await queryRunner.query(`CREATE TABLE "system_configurations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "configKey" character varying(100) NOT NULL, "configValue" text, "configValueJson" json, "configType" "public"."system_configurations_configtype_enum" NOT NULL DEFAULT 'text', "groupName" character varying(100) NOT NULL, "label" character varying(255) NOT NULL, "description" text, "isRequired" boolean NOT NULL DEFAULT false, "isPublic" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_7ca5b9b2b1141a786795e96fd0c" UNIQUE ("configKey"), CONSTRAINT "PK_9b5761d1315cd814c5df7b188bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3860b08dc211ff0dba637ec206" ON "system_configurations" ("isPublic") `);
        await queryRunner.query(`CREATE INDEX "IDX_45eca87556f114da4dd33faa12" ON "system_configurations" ("groupName") `);
        await queryRunner.query(`CREATE TYPE "public"."auth_tokens_type_enum" AS ENUM('login')`);
        await queryRunner.query(`CREATE TABLE "auth_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "token" character varying(255) NOT NULL, "type" "public"."auth_tokens_type_enum" NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "isUsed" boolean NOT NULL DEFAULT false, "applicantId" character varying(500), "ipAddress" character varying(45), "userAgent" character varying(500), "usedAt" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0db4d75e7b32888464cdf8e3745" UNIQUE ("token"), CONSTRAINT "PK_41e9ddfbb32da18c4e85e45c2fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a722572f722dab5fb4a2ededf9" ON "auth_tokens" ("token", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb45bf66617a6f7430e061ee79" ON "auth_tokens" ("email", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."evaluation_results_decision_enum" AS ENUM('lolos', 'tidak_lolos')`);
        await queryRunner.query(`CREATE TABLE "evaluation_results" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "application_id" uuid NOT NULL, "education_score" double precision, "experience_score" double precision, "skill_score" double precision, "total_score" double precision, "decision" "public"."evaluation_results_decision_enum", "score_detail" json, "evaluated_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_561d246e8634fece346e4b497ab" UNIQUE ("application_id"), CONSTRAINT "REL_561d246e8634fece346e4b497a" UNIQUE ("application_id"), CONSTRAINT "PK_c621da2265b8bed07a44a5d5fa6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "applicant_applicant_sources" ("applicant_id" uuid NOT NULL, "applicant_source_id" uuid NOT NULL, CONSTRAINT "PK_dbe377951831a03a24964f81058" PRIMARY KEY ("applicant_id", "applicant_source_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f08aeccd63be8976ed997c04cf" ON "applicant_applicant_sources" ("applicant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c09bd2f0f959ff1feb0111aebb" ON "applicant_applicant_sources" ("applicant_source_id") `);
        await queryRunner.query(`ALTER TABLE "pipeline_stages" ADD CONSTRAINT "FK_37b689c446ebe79ecd37e445735" FOREIGN KEY ("pipeline_id") REFERENCES "recruitment_pipelines"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pipeline_stages" ADD CONSTRAINT "FK_8d80115658205822fa35ec0d88e" FOREIGN KEY ("stage_template_id") REFERENCES "stage_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vacancies" ADD CONSTRAINT "FK_a18e1254d6de40d2307f7e13d48" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vacancies" ADD CONSTRAINT "FK_3a23dde4ad85c9d976c7e0415cf" FOREIGN KEY ("pipeline_id") REFERENCES "recruitment_pipelines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vacancies" ADD CONSTRAINT "FK_7afb699b382626b3d6927038bdd" FOREIGN KEY ("job_category_id") REFERENCES "job_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stage_activities" ADD CONSTRAINT "FK_b5e27ea7b69b9c7892693be65a5" FOREIGN KEY ("application_id") REFERENCES "applications"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stage_activities" ADD CONSTRAINT "FK_4756fc9015067391184fd54f1d8" FOREIGN KEY ("stage_id") REFERENCES "pipeline_stages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_notes" ADD CONSTRAINT "FK_1a5375c61bc031bba625c02096d" FOREIGN KEY ("application_id") REFERENCES "applications"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_194d0fca275b8661a56e486cb64" FOREIGN KEY ("applicant_id") REFERENCES "applicants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_98eda645f55272b67d408cc5c99" FOREIGN KEY ("vacancy_id") REFERENCES "vacancies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_1d7dd53e64a0bd2478cd0a346ac" FOREIGN KEY ("pipeline_id") REFERENCES "recruitment_pipelines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_6d2cfb5836752ed24674b795b85" FOREIGN KEY ("current_stage_id") REFERENCES "pipeline_stages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant_addresses" ADD CONSTRAINT "FK_b04ef238238c269a47f8ba8566f" FOREIGN KEY ("applicant_id") REFERENCES "applicants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant_job_histories" ADD CONSTRAINT "FK_5780104bfa1f4c93c0ab4d545f8" FOREIGN KEY ("applicant_id") REFERENCES "applicants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant_job_histories" ADD CONSTRAINT "FK_16728adb24fca50b38fe1d71979" FOREIGN KEY ("cv_document_id") REFERENCES "cv_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_documents" ADD CONSTRAINT "FK_13f6e65f840ee1723474d3a2e20" FOREIGN KEY ("application_id") REFERENCES "applications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant_educations" ADD CONSTRAINT "FK_9118088804834731703df05ed69" FOREIGN KEY ("applicant_id") REFERENCES "applicants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant_educations" ADD CONSTRAINT "FK_92b6c0b65a796e1f42d954eee76" FOREIGN KEY ("cv_document_id") REFERENCES "cv_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant_project_histories" ADD CONSTRAINT "FK_a830f5c9c95b83423b4843da0f7" FOREIGN KEY ("applicant_id") REFERENCES "applicants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant_identities" ADD CONSTRAINT "FK_d63e658372fdff760e8b5fafc43" FOREIGN KEY ("applicant_id") REFERENCES "applicants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_63c92c51cd7fd95c2d79d709b61" FOREIGN KEY ("uploaded_by") REFERENCES "applicants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_templates" ADD CONSTRAINT "FK_6d6804a42c18cd79cd05c7d9ba2" FOREIGN KEY ("stage_template_id") REFERENCES "stage_templates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluation_results" ADD CONSTRAINT "FK_561d246e8634fece346e4b497ab" FOREIGN KEY ("application_id") REFERENCES "applications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant_applicant_sources" ADD CONSTRAINT "FK_f08aeccd63be8976ed997c04cf1" FOREIGN KEY ("applicant_id") REFERENCES "applicants"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "applicant_applicant_sources" ADD CONSTRAINT "FK_c09bd2f0f959ff1feb0111aebb4" FOREIGN KEY ("applicant_source_id") REFERENCES "applicant_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "applicant_applicant_sources" DROP CONSTRAINT "FK_c09bd2f0f959ff1feb0111aebb4"`);
        await queryRunner.query(`ALTER TABLE "applicant_applicant_sources" DROP CONSTRAINT "FK_f08aeccd63be8976ed997c04cf1"`);
        await queryRunner.query(`ALTER TABLE "evaluation_results" DROP CONSTRAINT "FK_561d246e8634fece346e4b497ab"`);
        await queryRunner.query(`ALTER TABLE "notification_templates" DROP CONSTRAINT "FK_6d6804a42c18cd79cd05c7d9ba2"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_63c92c51cd7fd95c2d79d709b61"`);
        await queryRunner.query(`ALTER TABLE "applicant_identities" DROP CONSTRAINT "FK_d63e658372fdff760e8b5fafc43"`);
        await queryRunner.query(`ALTER TABLE "applicant_project_histories" DROP CONSTRAINT "FK_a830f5c9c95b83423b4843da0f7"`);
        await queryRunner.query(`ALTER TABLE "applicant_educations" DROP CONSTRAINT "FK_92b6c0b65a796e1f42d954eee76"`);
        await queryRunner.query(`ALTER TABLE "applicant_educations" DROP CONSTRAINT "FK_9118088804834731703df05ed69"`);
        await queryRunner.query(`ALTER TABLE "cv_documents" DROP CONSTRAINT "FK_13f6e65f840ee1723474d3a2e20"`);
        await queryRunner.query(`ALTER TABLE "applicant_job_histories" DROP CONSTRAINT "FK_16728adb24fca50b38fe1d71979"`);
        await queryRunner.query(`ALTER TABLE "applicant_job_histories" DROP CONSTRAINT "FK_5780104bfa1f4c93c0ab4d545f8"`);
        await queryRunner.query(`ALTER TABLE "applicant_addresses" DROP CONSTRAINT "FK_b04ef238238c269a47f8ba8566f"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_6d2cfb5836752ed24674b795b85"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_1d7dd53e64a0bd2478cd0a346ac"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_98eda645f55272b67d408cc5c99"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_194d0fca275b8661a56e486cb64"`);
        await queryRunner.query(`ALTER TABLE "application_notes" DROP CONSTRAINT "FK_1a5375c61bc031bba625c02096d"`);
        await queryRunner.query(`ALTER TABLE "stage_activities" DROP CONSTRAINT "FK_4756fc9015067391184fd54f1d8"`);
        await queryRunner.query(`ALTER TABLE "stage_activities" DROP CONSTRAINT "FK_b5e27ea7b69b9c7892693be65a5"`);
        await queryRunner.query(`ALTER TABLE "vacancies" DROP CONSTRAINT "FK_7afb699b382626b3d6927038bdd"`);
        await queryRunner.query(`ALTER TABLE "vacancies" DROP CONSTRAINT "FK_3a23dde4ad85c9d976c7e0415cf"`);
        await queryRunner.query(`ALTER TABLE "vacancies" DROP CONSTRAINT "FK_a18e1254d6de40d2307f7e13d48"`);
        await queryRunner.query(`ALTER TABLE "pipeline_stages" DROP CONSTRAINT "FK_8d80115658205822fa35ec0d88e"`);
        await queryRunner.query(`ALTER TABLE "pipeline_stages" DROP CONSTRAINT "FK_37b689c446ebe79ecd37e445735"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c09bd2f0f959ff1feb0111aebb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f08aeccd63be8976ed997c04cf"`);
        await queryRunner.query(`DROP TABLE "applicant_applicant_sources"`);
        await queryRunner.query(`DROP TABLE "evaluation_results"`);
        await queryRunner.query(`DROP TYPE "public"."evaluation_results_decision_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb45bf66617a6f7430e061ee79"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a722572f722dab5fb4a2ededf9"`);
        await queryRunner.query(`DROP TABLE "auth_tokens"`);
        await queryRunner.query(`DROP TYPE "public"."auth_tokens_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45eca87556f114da4dd33faa12"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3860b08dc211ff0dba637ec206"`);
        await queryRunner.query(`DROP TABLE "system_configurations"`);
        await queryRunner.query(`DROP TYPE "public"."system_configurations_configtype_enum"`);
        await queryRunner.query(`DROP TABLE "notification_templates"`);
        await queryRunner.query(`DROP TABLE "files"`);
        await queryRunner.query(`DROP TYPE "public"."files_filetype_enum"`);
        await queryRunner.query(`DROP TABLE "applicants"`);
        await queryRunner.query(`DROP TYPE "public"."applicants_availability_enum"`);
        await queryRunner.query(`DROP TYPE "public"."applicants_maritalstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."applicants_gender_enum"`);
        await queryRunner.query(`DROP TABLE "applicant_sources"`);
        await queryRunner.query(`DROP TABLE "applicant_identities"`);
        await queryRunner.query(`DROP TYPE "public"."applicant_identities_identitytype_enum"`);
        await queryRunner.query(`DROP TABLE "applicant_project_histories"`);
        await queryRunner.query(`DROP TABLE "applicant_educations"`);
        await queryRunner.query(`DROP TYPE "public"."applicant_educations_level_enum"`);
        await queryRunner.query(`DROP TABLE "cv_documents"`);
        await queryRunner.query(`DROP TABLE "applicant_job_histories"`);
        await queryRunner.query(`DROP TYPE "public"."applicant_job_histories_employeestatus_enum"`);
        await queryRunner.query(`DROP TABLE "applicant_addresses"`);
        await queryRunner.query(`DROP TYPE "public"."applicant_addresses_addresstype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9212e477141318a97e35701ef8"`);
        await queryRunner.query(`DROP TABLE "applications"`);
        await queryRunner.query(`DROP TYPE "public"."applications_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d3769eb65b81f027908bdcd0e1"`);
        await queryRunner.query(`DROP TABLE "application_notes"`);
        await queryRunner.query(`DROP TABLE "stage_activities"`);
        await queryRunner.query(`DROP TYPE "public"."stage_activities_status_enum"`);
        await queryRunner.query(`DROP TABLE "vacancies"`);
        await queryRunner.query(`DROP TYPE "public"."vacancies_requirededucation_enum"`);
        await queryRunner.query(`DROP TYPE "public"."vacancies_salaryperiod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."vacancies_workmodel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."vacancies_employmenttype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."vacancies_jobtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."vacancies_status_enum"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP TABLE "job_categories"`);
        await queryRunner.query(`DROP TABLE "recruitment_pipelines"`);
        await queryRunner.query(`DROP TABLE "pipeline_stages"`);
        await queryRunner.query(`DROP TABLE "stage_templates"`);
    }

}
